name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # scarica codice dalla repo
      - name: Checkout
        uses: actions/checkout@v4
      
        # prepara la cartella /website per la pubblicazione
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './website' 

        # pubblica il sito
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
